# docker-compose-hardware.yml
version: '3'

services:
  ros2_micro_ros_agent:
    container_name: ros2_micro_ros_agent
    image: frankjoshua/ros2-micro-ros-agent
    network_mode: host
    ipc: host
    pid: host
    privileged: true
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'

  ros2_gps:
    container_name: ros2_gps
    image: frankjoshua/ros2-gps
    network_mode: host
    ipc: host
    pid: host
    privileged: true
    devices:
      - "/dev/gps:/dev/ttyACM0"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'

  ros2_imu:
    container_name: ros2_imu
    image: frankjoshua/ros2-imu
    network_mode: host
    ipc: host
    pid: host
    privileged: true
    devices:
      - "/dev/imu:/dev/ttyACM0"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'

  ros2_ydlidar_x4:
    container_name: ros2_ydlidar_x4
    image: frankjoshua/ros2-ydlidar-x4
    network_mode: host
    ipc: host
    pid: host
    privileged: true
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'
