---
- hosts: all

  vars:
    # Normally set in anisbile/production
    ros_master_uri: 'http://192.168.33.58:11311'
    ros_ip: '192.168.33.58'
    home_dir: '/home/vagrant'

  roles:
    - name: ansible-role-ros
      ros_configuration: desktop-full
      become: yes

  tasks:

    - name: Clone club robot repo
      ansible.builtin.git:
        repo: 'https://github.com/frankjoshua/robomo-club-robot.git'
        dest: '/home/robot/robomo-club-robot'
      become: yes
        
    - name: export ros_master_uri
      lineinfile:
        dest: '{{ home_dir }}/.bashrc'
        state: present
        regexp: '^source /opt/ros/melodic/setup.bash'
        line: 'source /opt/ros/melodic/setup.bash'
      become: yes

    - name: export ros_master_uri
      lineinfile:
        dest: '{{ home_dir }}/.bashrc'
        state: present
        regexp: '^export ROS_MASTER_URI='
        line: 'export ROS_MASTER_URI={{ ros_master_uri }}'
      become: yes

    - name: export ros_ip
      lineinfile:
        dest: '{{ home_dir }}/.bashrc'
        state: present
        regexp: '^export ROS_IP='
        line: 'export ROS_IP={{ ros_ip }}'
      become: yes
