---
- hosts: all

  roles:
    - name: ansible-role-ros
      ros_configuration: desktop-full
      become: yes

  tasks:
    - name: export ros_master_uri
      lineinfile:
        dest: /home/vagrant/.bashrc
        state: present
        regexp: '^source /opt/ros/melodic/setup.bash'
        line: 'source /opt/ros/melodic/setup.bash'
      become: yes

    - name: export ros_master_uri
      lineinfile:
        dest: /home/vagrant/.bashrc
        state: present
        regexp: '^export ROS_MASTER_URI='
        line: 'export ROS_MASTER_URI={{ ros_master_uri }}'
      become: yes

    - name: export ros_ip
      lineinfile:
        dest: /home/vagrant/.bashrc
        state: present
        regexp: '^export ROS_IP='
        line: 'export ROS_IP={{ ros_ip }}'
      become: yes
