
Vagrant.configure("2") do |config|

  config.vm.define "workstation" do |workstation|
    # workstation.vm.synced_folder "./catkin_ws", "/catkin_ws"
    workstation.vm.hostname = "workstation"
    workstation.vm.network "public_network", bridge: "enp3s0"
    workstation.vm.network :private_network, ip: "192.168.33.58"
    workstation.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      vb.gui = true
      # Customize the amount of memory on the VM:
      vb.memory = "4096"
      vb.cpus = 6
    end
    workstation.vm.box = "ubuntu/bionic64"
    workstation.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y ubuntu-desktop
      SHELL
    workstation.vm.provision :ansible do |ansible|
      ansible.galaxy_role_file = "requirements.yml"
      ansible.playbook = "ros_gazebo.yml"
    end
  end

  #
  # Run Ansible from the Vagrant Host
  #
  # ENV['ANSIBLE_ROLES_PATH'] = ".vagrant/roles:./roles"
  # ENV['ANISBLE_STDOUT_CALLBACK'] = "debug"
  # config.vm.provision "ansible" do |ansible|
  #   ansible.galaxy_roles_path = '.vagrant/roles'
  #   ansible.galaxy_command = 'ansible-galaxy install --role-file=%{role_file} --roles-path=%{roles_path}'
  #   ansible.galaxy_role_file = 'ansible/requirements.yml'
  #   ansible.playbook = "ansible/playbook.yml"
  #   ansible.inventory_path = "ansible/production"
  # end
end