---
- include: ssh.yml

- hosts: robot
  vars:
    lsb_release: bionic
    pip_install_packages:
      - name: docker

  roles:
    # Jetson Nano already has Docker installed
    # - { role: geerlingguy.docker, become: true}
    - { role: geerlingguy.pip, become: true }

  tasks:
    - name: Check that robot is online
      ping:

    - name: Start ROS master docker container
      docker_container:
        name: ros_master
        image: 'frankjoshua/ros-master:{{ cpu_arch }}'
        network_mode: 'host'
        restart_policy: 'unless-stopped'
        env:
          ROS_MASTER_URI: 'http://{{ ansible_ssh_host }}:11311'
          ROS_IP: '{{ ansible_ssh_host }}'
      become: true

    - name: Add apt key for ROS
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
      become: true

    - name: Setup PPA for ROS
      apt_repository:
        repo: deb http://packages.ros.org/ros/ubuntu {{ lsb_release }} main
        state: present
      become: true

    - name: Instal ROS from apt
      apt:
        name: ros-melodic-desktop-full
        state: latest
        update_cache: yes
      become: true

    - name: Source ROS from .bashrc
      lineinfile:
        dest: /home/operator/.bashrc
        state: present
        regexp: '^source /opt/ros/melodic/setup.bash'
        line: 'source /opt/ros/melodic/setup.bash'
      become: yes
