---
- hosts: robot
  vars:
    ros_ip: '{{ ansible_default_ipv4.address }}'
    ros_master_uri: 'http://{{ ansible_default_ipv4.address }}:11311'
    pull_image: true

  roles:
    - { role: ansible-role-ros-master, become: yes }
    - { role: ansible-role-ros-bridge-suite, become: yes }
    - { role: ansible-role-ros-jviz, become: yes }
    - { role: ansible-role-ros-webviz, become: yes }

  tasks:
    - name: export ros_master_uri
      lineinfile:
        dest: /home/operator/.bashrc
        state: present
        regexp: '^export ROS_MASTER_URI='
        line: 'export ROS_MASTER_URI={{ ros_master_uri }}'
      become: yes

    - name: export ros_ip
      lineinfile:
        dest: /home/operator/.bashrc
        state: present
        regexp: '^export ROS_IP='
        line: 'export ROS_IP={{ ros_ip }}'
      become: yes
