---
- hosts: robot_hardware
  vars:
    ros_ip: '{{ ansible_default_ipv4.address }}'
    ros_master_uri: 'http://{{ ansible_default_ipv4.address }}:11311'
  tasks:
    - name: Start ROS Serial Node
      docker_container:
        name: 'ros_serial'
        image: 'frankjoshua/ros-serial'
        network_mode: 'host'
        restart_policy: 'unless-stopped'
        devices:
          - '/dev/ttyACM0:/dev/arduino'
        env:
          ROS_MASTER_URI: '{{ ros_master_uri }}'
          ROS_IP: '{{ ros_ip }}'
        log_driver: json-file
        log_options:
          max-size: 10m
          max-file: 3
      become: yes

    - name: Start ydlidar_x4 laser Node
      docker_container:
        name: 'ros_ydlidar_x4'
        image: 'frankjoshua/ros-ydlidar-x4'
        network_mode: 'host'
        restart_policy: 'unless-stopped'
        devices:
          - '/dev/ttyUSB0:/dev/ydlidar'
        env:
          ROS_MASTER_URI: '{{ ros_master_uri }}'
          ROS_IP: '{{ ros_ip }}'
        log_driver: json-file
        log_options:
          max-size: 10m
          max-file: 3
      become: yes
