---
- hosts: testing-server

  tasks:
    - name: Install Infraspec
      pip:
        name: testinfra
      become: yes

    - name: Copy private keys
      copy:
        src: './files/ssh_keys/robot_id_rsa'
        dest: "/home/{{ lookup('env','USER') }}/.ssh/robot_id_rsa"
        owner: "{{ lookup('env','USER') }}"
        mode: 0600
      become: yes
